### ISSUE TITLE
Wrappers for Node.js

### ISSUE THREAD

**Issue by olalonde** [obuchtala/swig#1]
Hey, I'll try to see what I can do to make this compatible with Node.js. Actually if you have time maybe you could help me get started? Here's a tuto on writing native Node.js extensions - I hope it's not too outdated (wrote it a couple months ago): http://syskall.com/how-to-write-your-own-native-nodejs-extension/index.html/ 

Other reference: https://www.cloudkick.com/blog/2010/aug/23/writing-nodejs-native-extensions/

Actually there doesn't seem to be anything much very Node.js specific except for 1 or 2 lines. My memory is a bit blurry... wrote this a long time ago and I'm not very good with C++!

**Comment by johncant** [comment]
I've been having a look at this (Sorry @oliver---- that I haven't done anything at all in the original writing of swig-v8) and I've found some bugs and figured out the basics of how to support node. The only problem is, I don't know enough about SWIG yet. I'll try and write some tests to verify the bugs I think I've found.

@olalonde, you probably already know given that I learned how to write native node modules using your tutorials, but I think all that has to be done is:

(1) Include the node headers in the output
(2) Change the generated initialize function so that you can pass a target object to initialize as the module rather than include the module in the global scope.
(3) Make a void init(v8::Handle&lt;v8::Object&gt;) function and use the NODE_MODULE macro.

**Comment by obuchtala** [comment]
Hi,

Currently I am a bit short of time to get this really going.
Thank you for the suggestions.

Already any work on that done?

Cheers,
Oliver

**Comment by obuchtala** [comment]
@johncant: if you have any commits, don't hesitate to send a pull request ;)

**Comment by johncant** [comment]
Nothing I'd consider worth committing :(

I'll put something into a Gist if it would help, but you guys probably already know everything I know. I've been able to manually edit the output from swig-v8 to the point where it can be required by node.js.

**Comment by johncant** [comment]
https://gist.github.com/4128311

**Comment by obuchtala** [comment]
@johncant item 2) is done

**Comment by obuchtala** [comment]
about 1) and 3)
I would suggest to do this by providing an i.file (i.e., swig configuration file)

**Comment by johncant** [comment]
Wow!

**Comment by obuchtala** [comment]
Basically, this is working now.

There are the following things to do to use this feature:
- including a provided node swig file:
  
  ```
  %include <node.i>
  ```
- defining the node module initializer:
  
  ```
  %node(<module_name>)
  ```
- run swig with 'no-moduleobject' option:
  
  ```
  swig -javascript -v8 -no-moduleobject 
  ```

**Comment by obuchtala** [comment]
Find an example here:
https://gist.github.com/4489360

**Comment by johncant** [comment]
Awesome! Your gist was extremely helpful. My node.js looked for the "init" symbol, so I've hacked it into working. I'll submit a pull request!

**Comment by johncant** [comment]
node-gyp doesn't look for the "init" symbol, but node-waf does. Solution: use node-gyp since node-waf is deprecated

**Comment by obuchtala** [comment]
hmmmmkay.

just checked the current way. should we support the old way nevertheless?

**Comment by johncant** [comment]
The use case would be if you were building an extension for use with an older version of node.js, but I don't know whether node applications developers tend to constantly upgrade or stick with the same node version. IMHO, every npm package author should write for an up-to-date node.js, so we shouldn't bother, but it's really up to you. We already have the code.
