### ISSUE TITLE
V8 version compatibilities

### ISSUE THREAD

**Issue by obuchtala** [obuchtala/swig#12]
V8 lacks a version preprocessor macro (see https://code.google.com/p/v8/issues/detail?id=1844).
Different versions of v8 need (slightly) different wrapper code.

We could
- switch the generated wrapper code via swig command line flag
- generate uni-version code with pre-proc macro switches and leave it to the user to define the correct v8 version macro

IMO it would be desirable that a bundled version of swig would create code for the default v8 version for the specific platform.
This could be detected during swig configuration time and set a pre-proc macro that defines the default output mode.

**Comment by wsfulton** [comment]
it is pretty piss poor that there is no macro for the version. It can't be hard to create a patch to get one in. Could you try that as this will make it much easier for SWIG users going forwards?

Given the current situation though, I suggest you solve it with the 2nd bullet point approach. Choose a recent version (say the latest or the version shipped with LTS Ubuntu 12.04). At this stage given how new SWIG for JavaScript is, you probably won't be concerned with older versions of Javascript. If you can get a macro defining the version number in the very next release of v8, then SWIG can start to use it ... if the macro is not defined, then assume the version prior to the macro being introduced.

SWIG always outputs the same code given the same inputs on all platforms. I don't want that to change. I really think urgent priority should be given to patching v8 to have a version macro like all the other target languages. It is a joke that they don't have this already.

**Comment by obuchtala** [comment]
@wsfulton  Thanks, that helps.I initiated a pull request for a v8 version macro (https://github.com/v8/v8/pull/11).

Still we have to deal with the absence of such a macro for the current common binaries (e.g., for LTS Ubuntu 12.04). They are kind of in a stone-age, and out-of-the-box we will have to serve a rather old version of v8 (2.0.x). This would probably be also the case with Travis-CI.
Other people and projects (e.g., node.js 0.10.x) are already working with v8 > 3.20.

So it remains for me to decide which is an appropriate default.

**Comment by ewmailing** [comment]
This patch is my recommended way of dealing with it:
https://github.com/ewmailing/swig-v8/commit/6d73f929f4e698357de0f8f84b0b08a0f43e13b1

The user specifies a switch like -api V8_3_14  and the correct #define gets written at the top. 

I don't have a strong opinion on which version should be the default. I decided to make my life more difficult and accepted the other patches that assumed the latest v8 is the default, meaning I need to always specify that command line switch.

**Comment by obuchtala** [comment]
Hmmm...

When I understand William's guideline right, we should generate the same code all the time
and leave it to the embedding project to set the `#define` correctly.

This is fine for me, however, it has the consequence that the test-suite and examples will not 
run out-of-the-box in general when shipped as binaries.
For Travis-CI we would add appropriate flags - which we would need to keep up2date (sorry - lacking experience here).

@wsfulton more advice :)

**Comment by ewmailing** [comment]
So I think my proposal is a nice compromise that both satisfies Willam's requirement as well as not make it a complete nuisance for people using it.

By default (with no switches), the generated code has no #defines and it is up to the user to figure out how to inject the correct #defines. But for convenience, the embedding project may opt to generate SWIG code that has the desired #define already written at the top.

**Comment by ewmailing** [comment]
I feel I need I want to clarify the default case in case there is a misunderstanding. 

With no switches, the generated SWIG code should be able to compile against a specific version of v8 that we designate as the default. As long as the user is using that version of v8, they should not have to specify anything further and things should just work. (As I said earlier, I don't know what the blessed version should be.)

**Comment by obuchtala** [comment]
Me neither ;)

Maybe we should bless:

> Travis CI virtual machines are based on Ubuntu 12.04 LTS Server Edition 64 bit.

Lets wait for William.

**Comment by obuchtala** [comment]
Damn. How can one create a library without having a version macro... ts ts ts...
They are making use of such regularly with other APIs...

**Comment by ewmailing** [comment]
If you think think Google v8 is piss poor for missing blindingly obvious things, you haven't dealt with the Android NDK which is far worse. I'm in the unfortunate position of dealing with v8 on Android, so I'm doing everything I can to make life not suck even more.

**Comment by wsfulton** [comment]
Re dealing with the absence of a version macro, you might be able to 'detect' the version to some degree by the absence or existence of some other macros shipped with v8. Does SWIG need to support v2.0.x if things have moved on a lot since this release? If you don't then hopefully you can find a macro to differentiate v3.20.x and lower and generate code to just #error out for anything less than v3.20.x. Bah, what a nuisance this all is.

Anyway, for Travis, we could test with v3.20.x or any version you fancy. The solution is to use a PPA containing whatever version you want as they support installing personal PPAs - http://about.travis-ci.org/docs/user/build-configuration/#Using-3rd-party-PPAs. It might mean creating a personal PPA with the chosen version of v8, but I don't think that is too hard to achieve. Travis are fairly up to date with NodeJS and support it as a first class target - http://about.travis-ci.org/blog/first_class_nodejs_support_on_travis_ci/. Probably Travis have a PPA for this we could use, we'd just need to ask them. I'm assuming that we could then just use the v8 that NodeJS uses.

The version you choose to 'bless' really depends on what version macro tricks you can come up with. 

@ewmailing re the -api switch... this is just a command line option that you can already achieve with a simple %begin block. I'd rather use existing mechanisms (and document with an example) than invent another switch.

```
%begin %{
#define SWIG_V8_VERSION 0x032107
%}
```

Then the SWIG generated code uses it like:

```
#if (SWIG_V8_VERSION >= 0x032000)
// ...
#endif
```

@oliver--- I see you chose in your v8 version patch to break the version into 3 different components. That does work, but more commonly used seems to be a hex version such as PY_VERSION_HEX or SWIG_VERSION is nicer to deal with as it is just one macro.

**Comment by ewmailing** [comment]
On 9/1/13, William S Fulton notifications@github.com wrote:

> Re dealing with the absence of a version macro, you might be able to
> 'detect' the version to some degree by the absence or existence of some
> other macros shipped with v8. Does SWIG need to support v2.0.x if things
> have moved on a lot since this release? If you don't then hopefully you can
> find a macro to differentiate v3.20.x and lower and generate code to just
> #error out for anything less than v3.20.x. Bah, what a nuisance this all
> is.

Things have not moved on. I am stuck on the original version SWIG v8
was written for (appears to be 3.14). I am tied to the Appcelerator
ecosystem. They are a large force in native mobile apps + Javascript,
and for the moment, their v8 is version is not moving.

And it looks like the NodeJS version is also using 3.14.

> @ewmailing re the -api switch... this is just a command line option that you
> can already achieve with a simple %begin block. I'd rather use existing
> mechanisms (and document with an example) than invent another switch.
> 
> ```
> %begin %{
> #define SWIG_V8_VERSION 0x032107
> %}
> ```
> 
> Then the SWIG generated code uses it like:
> 
> ```
> #if (SWIG_V8_VERSION >= 0x032000)
> // ...
> #endif
> ```

Unless there is a way to specify the above via command line invocation
when invoking SWIG, this doesn't solve the problem.  The .i resources
are shared resources belonging to the library I'm trying to bind to
(and not necessarily me) and they are intended to be agonistic about
which target language (Python, Lua, Javascript), which Javascript
intepretor (JSCore, v8), and which version (3.14, 3.20). That %begin
code doesn't belong in every .i file in the universe and won't
actually solve the problem.

**Comment by wsfulton** [comment]
If 3.14 is being used all over the place, consider making that the minimum and default version?

@ewmailing, Are you aware of the preprocessor directive for each target language - SWIGJAVASCRIPT in this case. The %begin code block would then be:

```
#ifdef SWIGJAVASCRIPT
 %begin %{
 #define SWIG_V8_VERSION 0x032107
 %}
#endif  
```

SWIG is designed to customise the code (additional code, typemaps and features etc) using interface files. Are you saying you can't edit an interface file? I hope not. If you are, you need to revisit your design! I find it hard to believe that any interface files are 100% language agnostic, surely you can get the interface files patched? Maybe, I've misunderstood your situation, but I'm very reluctant to accept additional command line options that replicate normal code control, just because one user cannot organise to edit an interface file.

Note that you can also define your own preprocessor macros using swig -D but in order to act on it you still need to write code in the interface file.

**Comment by ewmailing** [comment]
On 9/2/13, William S Fulton notifications@github.com wrote:

> If 3.14 is being used all over the place, consider making that the minimum
> and default version?

I personally don't have a problem with that. But it just pushes the
problem to anybody using a different version of v8. (I agree, this
problem caused by the lack of version identifiers in v8 sucks.)

> @ewmailing, Are you aware of the preprocessor directive for each target
> language - SWIGJAVASCRIPT in this case.

Yes, I am using that. However I have not had to dive much deeper than
that. SWIG is doing its job and insulating me from the very low
implementation details (as it should ). (But even if it didn't, it
should be like your first requirement of SWIG where all v8 version
code paths are generated.)

The problem is that say for example, a famous library like OpenAL, I
shouldn't be restricting which version of v8 the OpenAL user wants to
compile against. My Appcelerator or NodeJS environment requires me to
use 3.14, but there is nothing about OpenAL that restricts it to that.
Any OpenAL user should be able to take that same/shared al.i file and
use it for any of the SWIG supported v8 versions.

Categorically, this switch is a function of SWIG, not of a .i
implementation. (This should be a function of v8.h and its version
identifiers, but we already established that Google dropped the ball
on this one and we're in damage control mode. I argue that the damage
should be contained to an optional switch in the v8/SWIG generator and
not pushed into (many) library .i descriptions that can and should be
otherwise agnostic.)

**Comment by obuchtala** [comment]
Thanks William!

I have come to a decision :)

For the default we choose the v8 shipped with node.js v0.8.25 which Travis-CI uses currently.
From a look into node.js [changelog](https://github.com/joyent/node/blob/master/ChangeLog#L1111) this is version [3.11.10](https://github.com/joyent/node/blob/master/ChangeLog#L1272).

Also we make node.js the first class interpreter for tests and examples. Node.js is easier to install than building v8 and works out-of-the-box on all platforms.

For the other v8 versions we introduce version switches for the `V8_VERSION` macro (which will hopefully be provided as built-in in future).

**Comment by obuchtala** [comment]
@ewmailing What do you think about such a solution:

``` C
%define %swig_v8_define_version(version)
%begin %{
#ifndef V8_VERSION
#define V8_VERSION version
#endif
%}
%enddef

#ifdef SWIGJAVASCRIPT
#ifdef SWIG_V8_VERSION
%swig_v8_define_version(SWIG_V8_VERSION)
#endif
#endif
```

This could be provided as helper macro in helper i-file.

One would then add the version `#define` via

``` bash
$ swig -javascript -v8 -DSWIG_V8_VERSION=0x032107
```

**Comment by obuchtala** [comment]
We would just add this into one of the swig-v8 i-files.
Then we have both things, no extra option, and no need to touch your project i-files

**Comment by obuchtala** [comment]
I just stumbled over a rather new issue: https://codereview.chromium.org/23723003
There seem to be private macros which the proposed patch should make public.
However, they rejected it. I am trying to push a bit to reopen it... let's hope.

**Comment by ewmailing** [comment]
On 9/2/13, Oliver Buchtala notifications@github.com wrote:

> We would just add this into one of the swig-v8 i-files.
> Then we have both things, no extra option, and no need to touch your project
> i-files

I think this sounds like a reasonable solution.

**Comment by obuchtala** [comment]
I implemented a first version: a48438c562b3f1601e5bbc9cedcf9f124af97975

@ewmailing Could you evaluate if the solution is applicable to your use-case?

**Comment by ewmailing** [comment]
On 9/3/13, Oliver Buchtala notifications@github.com wrote:

> I implemented a first version: a48438c562b3f1601e5bbc9cedcf9f124af97975
> 
> @ewmailing Could you evaluate if the solution is applicable to your
> use-case?

The generation is a little off. I get this:

#ifndef 0x031400
#define 0x031400 0x031400
#endif

If I manually modify the above block to:
#ifndef SWIG_V8_VERSION
#define SWIG_V8_VERSION 0x031400
#endif

it builds okay for me.

An aside, I just hit a new problem with the use of C99 INFINITY. I
have APIs that expect a float, so when the SWIG API is called to
convert double to float, an overflow check is run and my code throws
an error.

SWIGINTERN int
SWIG_AsVal_float SWIG_JSC_AS_DECL_ARGS(JSValueRef obj, float *val)
{
  double v;
  int res = SWIG_AsVal_double SWIG_JSC_AS_CALL_ARGS(obj, &v);
  if (SWIG_IsOK(res)) {
    if ((v < -FLT_MAX || v > FLT_MAX)) {
      return SWIG_OverflowError;
    } else {
      if (val) *val = (float)(v);
    }
  }
  return res;
}

If I remove the overflow check, my code seems to work.

I'm wondering, could this same technique be used to tell SWIG to
disable overflow checking?

**Comment by obuchtala** [comment]
> #ifndef 0x031400
> #define 0x031400 0x031400
> #endif

Oops. That's not what I wanted ;) Need to take a look again.

For the infinity problem an extra issue:  #16

> I'm wondering, could this same technique be used to tell SWIG to disable overflow checking?

What do you mean exactly?

**Comment by ewmailing** [comment]
> > I'm wondering, could this same technique be used to tell SWIG to disable
> > overflow checking?
> 
> What do you mean exactly?

This is a non-issue now since the other thing is actually a bug. But
in the case it was proper behavior, I wanted a way to disable overflow
checks either at generation or compile time.

**Comment by obuchtala** [comment]
@ewmailing To have overflow checks switchable, changes to the UTL would be necessary.
However, that's not really my territory... I don't know much about the details there.
So, maybe you could make a general SWIG feature request.

**Comment by ewmailing** [comment]
On 9/4/13, Oliver Buchtala notifications@github.com wrote:

> > #ifndef 0x031400
> > #define 0x031400 0x031400
> > #endif
> 
> Oops. That's not what I wanted ;) Need to take a look again.

I think I fixed the problem. Changing the user variable to
SWIG_USE_V8_VERSION will sidestep the macro ambiguity problem:

%define %swig_v8_define_version(version)
%begin %{
#ifndef SWIG_V8_VERSION
#define SWIG_V8_VERSION version
#endif
%}
%enddef

#ifdef SWIG_USE_V8_VERSION
%swig_v8_define_version(SWIG_USE_V8_VERSION)
#else
// HACK: defining a default version
%swig_v8_define_version(SWIG_USE_V8_VERSION)
#endif

To invoke,
./preinst-swig -javascript -v8  -DSWIG_USE_V8_VERSION=0x031400 foo.i

Sound good?

Thanks,
Eric

**Comment by obuchtala** [comment]
Yes, sounds good.
Or just USE_V8_VERSION, as it is only used during swig processing.

**Comment by obuchtala** [comment]
Am AFK until Monday...

**Comment by ewmailing** [comment]
On 9/6/13, Oliver Buchtala notifications@github.com wrote:

> Am AFK until Monday...

Thanks for the heads up. I just pushed this fix to my js_unit_tests branch.
I may start pushing my other fixes I've talked about in other threads
there too soon.

**Comment by obuchtala** [comment]
Cool.
I review it on monday.

**Comment by obuchtala** [comment]
I think we can consider this as solved.

**Comment by wsfulton** [comment]
@oliver---- did you get anywhere with the patch submission? I see https://github.com/v8/v8/pull/11 was closed and you needed to use a codereview site. Do you have a link to the patch on this site or anything else to monitor?

**Comment by obuchtala** [comment]
@wsfulton hmpf ... no. I found that recent issue https://codereview.chromium.org/23723003.
They have such macros ... private :(
The issue was rejected.
Should I repeat that process?

**Comment by wsfulton** [comment]
Yes, I really think we need to keep this topic on their radar and get a 
public version macro. It is vitally important for SWIG given API changes 
do happen.
